package com.cognizant.assignment.dto;

import lombok.AllArgsConstructor;

@AllArgsConstructor
public enum Status {
SUCCESS("SUCCESSFUL"),BAD_REQUEST("BAD_REQUEST"),INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),DUBLICATE_REFERENCE("DUPLICATE_REFERENCE"),INCORRECT_END_BALANCE("INCORRECT_END_BALANCE"),
    DUPLICATE_REFERENCE_INCORRECT_END_BALANCE("DUPLICATE_REFERENCE_INCORRECT_END_BALANCE");

private String value;
}
